module.exports = {
  redirect: 'http://google.com',
  image: 'static/mock.png',
  q: [
    {
      id: 4,
      name: "99lstwark",
      clone_of: "repulse",
      rom_of: "repulse",
      source_file: "pre90s/d_kyugo.cpp",
      description: "'99: The Last War (Kyugo)",
      year: 1985,
      manufacturer: "Crux / Kyugo",
      comment: null,
      driver_status: "good",
      dataset: "FinalBurn Neo (ClrMame Pro XML, Arcade only).dat",
      rank: -24.665771525764924,
    },
    {
      id: 4684,
      name: "pprobe",
      clone_of: null,
      rom_of: null,
      source_file: "pre90s/d_vastar.cpp",
      description: "Planet Probe (prototype?)",
      year: 1985,
      manufacturer: "Crux / Kyugo?",
      comment: "Prototype",
      driver_status: "good",
      dataset: "FinalBurn Neo (ClrMame Pro XML, Arcade only).dat",
      rank: -23.92161657320508,
    },
  ],
  dropdowns: {
    datasets: [
      "FinalBurn Neo (ClrMame Pro XML, Arcade only).dat",
      "FinalBurn Neo (ClrMame Pro XML, Neogeo only).dat",
    ],
    manufacturers: [
      "Konami",
      "Promat?",
      "bootleg",
      "Crux / Kyugo",
      "Crux / Proma",
      "Irem (Taito license)",
      "Irem",
      "Kaneko",
    ],
  },
};
